### ISSUE TITLE
GetAddesssApi has inconsistent name/spelling

### ISSUE THREAD

**Issue by Stoolbend** [getAddress/getAddress.Sdk#1]
The GetAddesssApi (getAddress.Sdk/GetAddesssApi.cs) has an inconsistent name to the rest of the SDK. Should it be called GetAddressApi? I imagine this would be a breaking change however.

**Comment by LeePaulSmith** [comment]
Wow! I am not sure how this has gone unnoticed for so long. Thanks for spotting this.

**Comment by Stoolbend** [comment]
No worries, I can make a PR this evening if you'd like me to fix? 👍

**Comment by LeePaulSmith** [comment]
Thanks but it's being done now.
