### ISSUE TITLE
Migrating to new package versions without the 'find' service

### ISSUE THREAD

**Issue by R3DsKZuLlZx** [getAddress/GetAddress.Sdk#18]
I am trying to migrate from version `2.7.0` of this package to version `3.4.1.`

I am using the now removed `find` endpoint for looking up address using a postcode.

Is there a way to achieve equivalent functionality using version `3.4.1` of the SDK?

If not, would I be ok to fork the library? I could be being blind, but I'm not seeing any licence attached.

Thanks in advance 😄

**Comment by LeePaulSmith** [comment]
Please contact getAddress support.

**Comment by R3DsKZuLlZx** [comment]
Thanks for your reply @LeePaulSmith 

I will email support and update this chain with the reply.

**Comment by R3DsKZuLlZx** [comment]
# Update 😀

Support have informed me that the find endpoint has been deprecated across the board and is no longer available for new users.

As of yet, I've not been given a timeframe for when this will be removed for existing users.

It looks like the alternative would be to use either the `autocomplete` endpoint, or the `location` endpoint.

They key difference at the moment seem to be:
- The shape of the data being returned
- The pricing tier required for the same amount of daily requests

## Using the `autocomplete` endpoint
- A post request to the `autocomplete` endpoint to get the suggestions
- A get request to the `get` endpoint with the `id` of the suggestion.

## Using the `location` endpoint
- A post request to the `location` endpoint to get the suggestions
- A get request to the `get-location` endpoint with the `id` of the suggestion.
