### ISSUE TITLE
Issue Unit Testing IAddressService.Get method

### ISSUE THREAD

**Issue by alistairdyer** [getAddress/getAddress.Sdk#2]
Hi,

I'm having issues mocking IAddressService.Get method as I cannot create a GetAddressResponse to return.  I need to do this so I can test my method when there is a success or failure coming from getAddress and I don't want to do an integration test for this.

Skeleton test class (using moq)

namespace PropertyAssistant.Property.Api.UnitTests.Functions
{
    using System;
    using System.IO;
    using System.Net.Http;
    using System.Security.Claims;
    using System.Text;
    using AutoMapper;
    using getAddress.Sdk.Api;
    using getAddress.Sdk.Api.Requests;
    using getAddress.Sdk.Api.Responses;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Moq;
    using Newtonsoft.Json;
    using PropertyAssistant.Common.Security;
    using PropertyAssistant.Common.Security.Authentication;
    using PropertyAssistant.Property.Api.Functions;
    using Shouldly;
    using Xunit;

    public class FindAddressFunctionTests
    {
        private readonly Mock<IAddressService> mockAddressService;
        private readonly FindAddressFunction target;

        public FindAddressFunctionTests()
        {
            this.mockAddressService = new Mock<IAddressService>();         
            this.target = new FindAddressFunction(this.mockAddressService.Object);
        }

        [Fact]
        public void Run_WhenAddressIsNotFound_ReturnsNotFoundObjectResult()
        {
            // Arrange
            this.mockAddressService.Setup(address => address.Get(It.IsAny<GetAddressRequest>(), It.IsAny<getAddress.Sdk.ApiKey>(), It.IsAny<HttpClient>()))
                .ReturnsAsync(new GetAddressResponse());
        }
    }
}

I cannot new up the GetAddresResponse class, it just says that it doesn't have a constructor with 0 arguments but it won't accept any arguments.  Because of this I can't return the response. 

Please accept my apologies for not understanding this correctly but I could really do with some help! 

Many thanks

**Comment by LeePaulSmith** [comment]
Hi Alistair,

The Get method returns sub-classes of the GetAddressResponse base class (either a GetAddressResponse.Success or GetAddressResponse.Failed). Please see: 
https://github.com/getAddress/getAddress.Sdk/blob/master/getAddress.Sdk.Standard/Api/Responses/GetAddressResponse.cs

In your case, the Setup method should return a moq'd or new instance of the GetAddressResponse.Failed class.

**Comment by alistairdyer** [comment]
Hi Lee,

Thanks very much for the quick reply, especially on a Sunday!  I've tried newing it up and mocking it but no joy.

var mockedResponse = new Mock<GetAddressResponse.Failed>();

Exception:
Parent does not have a default constructor. The default constructor must be explicitly defined.

If I try and new it up it also states that it doesn't have a 0 parameter constructor.  I've tried, based on the code in the repo doing:

var mockedResponse = new GetAddressResponse.Failed(statusCode: 404, reasonPhase: "Not Found", raw: "something raw", isSuccess: false);

Compile Error:
GetAddressResponse.Failed does not contain a constructor that takes 4 arguments.

Any help would be greatly appreciated.

Many thanks,

Alistair.

**Comment by LeePaulSmith** [comment]
Hi,

You can pass constructor arguments when you initialise Mock. Please see:
https://documentation.help/Moq/C681EE30.htm

I will look into making this easier to test by changing these constructors to public in the next version.

**Comment by alistairdyer** [comment]
Hi Lee,

I believe the problem is that it is a protected constructor, as there's no public constructor there's no way for me to pass in the values.  

If I follow the example above:

var mockedResponse = new Mock<GetAddressResponse.Failed>(404, "Not Found", "something raw", false).Object;

I still get:

Exception:
Parent does not have a default constructor. The default constructor must be explicitly defined

Any other pointers would be greatly appreciated!

Many thanks,

Alistair.

**Comment by LeePaulSmith** [comment]
Hi,
The Failed class constructor has three parameters and these should be passed in with an object[]
See:
https://documentation.help/Moq/C681EE30.htm

internal Failed(int statusCode, string reasonPhase, string raw)

**Comment by alistairdyer** [comment]
Hi Lee,

It's still giving the same error:

var mockedResponse = new Mock<GetAddressResponse.Failed>(new object[] { 404, "Not Found", "raw" }).Object;

or 

var mockedResponse = new Mock<GetAddressResponse.Failed>(MockBehavior.Strict, new object[] { 404, "Not Found", "raw" }).Object;

Exception:
Parent does not have a default constructor. The default constructor must be explicitly defined

Does this work for you?  I feel like I'm doing something really stupid!

Thanks for your help,

Alistair.

**Comment by LeePaulSmith** [comment]
Hi, 

Apologies, I'm not as familiar with moq as I should be. I'll look into changing this modifier from internal to public (or possibly creating an interface for the response) in our next release.

**Comment by alistairdyer** [comment]
Hi Lee,

Great idea!  It worked a charm!!  

Below is the code I used incase anyone has the same issue as me until.

Thanks very much for your help.

Cheers,

Alistair.

namespace Api.UnitTests
{
    using getAddress.Sdk.Api.Responses;

    /// <summary>
    /// Fake implementation to get around design issue with getAddress
    /// https://github.com/getAddress/getAddress.Sdk/issues/2.
    /// </summary>
    public class FakeGetAddressFailedResponse : GetAddressResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FakeGetAddressFailedResponse"/> class.
        /// </summary>
        /// <param name="statusCode">The status code.</param>
        /// <param name="reasonPhrase">The reason.</param>
        /// <param name="raw">The raw json.</param>
        /// <param name="isSuccess">Is successful.</param>
        public FakeGetAddressFailedResponse(int statusCode, string reasonPhrase, string raw, bool isSuccess)
            : base(statusCode, reasonPhrase, raw, isSuccess)
        {
        }
    }
}

**Comment by alistairdyer** [comment]
Tiny point but if you're doing a new release there is a typo in the internal constructor for the class:

public class Success : GetAddressResponse

internal Success(int statusCode, string **reasonPhase**, string raw, double latitude, double longitude, IEnumerable<Address> addresses) : base(statusCode, reasonPhase, raw, true)

Which I believe should be reasonPhrase

**Comment by LeePaulSmith** [comment]
Thanks, I'll correct this too.

**Comment by LeePaulSmith** [comment]
Corrected in release 1.7.5
