### ISSUE TITLE
API does not expose normalised postcode in result

### ISSUE THREAD

**Issue by acrov** [getAddress/getAddress.Sdk#4]
When you make a successful call to the rest API one of the really useful things you get back is a normalised, properly cased and properly spaced version of the postcode in the top level json property "postcode".  Unfortunately this does not appear to be exposed anywhere in the result object.

For example, an API call with a postcode of "gl538jt" returns a nicely formatted postcode of "GL53 8JT"; but this is not accessible in this lib.

**Comment by acrov** [comment]
Difficult to provide a code example for something that is missing from the code.  I'll try...

API returns postcode. e.g.
![image](https://user-images.githubusercontent.com/49073938/92107295-741f8700-eddd-11ea-9a70-1c6eaf55bf18.png)

The response model in the library does not include the postcode field.
![image](https://user-images.githubusercontent.com/49073938/92107378-944f4600-eddd-11ea-9dfd-b7d64f537714.png)

**Comment by LeePaulSmith** [comment]
Hi, The AddressService has the Get and GetExpanded methods. The GetExpanded method will return the postcode.

Please see our documentation (https://getaddress.io/documentation) for details.

`public interface IAddressService
    {
        ApiKey ApiKey { get; }
        Task<GetAddressResponse> Get(GetAddressRequest request, ApiKey apiKey = null, HttpClient httpClient = null);
        Task<GetExpandedAddressResponse> GetExpanded(GetAddressRequest request, ApiKey apiKey = null, HttpClient httpClient = null);
        Task<PlaceDetailsResponse> PlaceDetails(PlaceDetailsRequest request, ApiKey apiKey = null, HttpClient httpClient = null);
    }`

**Comment by acrov** [comment]
Awesome.  Thank you. Sorry to bother you.

**Comment by LeePaulSmith** [comment]
No problem.
